# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene':20}
limit = 1
twenty = db.establishments.find(query)
one = twenty = db.establishments.find(query).limit(limit)
# Use count_documents to display the number of documents in the result
db.establishments.count_documents(query)

# Display the first document in the results using pprint
for x in one:
    pprint(x)

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65b953683c56c5f054bb6d34'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [22]:
# Convert the result to a Pandas DataFrame
Results = []
for x in db.establishments.find({'scores.Hygiene':20}):
    Results.append(x)
ResultsDF = pd.DataFrame(Results)
    
# Display the number of rows in the DataFrame

len(ResultsDF)

41

In [21]:
# Display the first 10 rows of the DataFrame
ResultsDF.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65b953683c56c5f054bb6d34,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65b953683c56c5f054bb70af,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65b953683c56c5f054bb73b5,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65b953683c56c5f054bb75a9,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65b953683c56c5f054bb75b7,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,65b953683c56c5f054bb7f54,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,65b953683c56c5f054bb818b,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,65b953693c56c5f054bb96a2,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,65b953693c56c5f054bb9ae6,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,65b953693c56c5f054bba2f6,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [8]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query1 = {'LocalAuthorityName':'City of London Corporation','RatingValue':{'$gte':4}}
limit = 1
One = db.establishments.find(query1).limit(limit)
London = db.establishments.find(query1)


# Use count_documents to display the number of documents in the result

db.establishments.count_documents({'LocalAuthorityName':'City of London Corporation','RatingValue':{'$gte':4}})

#Display the first document in the results using pprint
for x in One:
    pprint(x)

{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65b953683c56c5f054bb874c'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [20]:
# Convert the result to a Pandas DataFrame
Londonlist = []
for x in db.establishments.find(query1):
    Londonlist.append(x)
    
LondonDF = pd.DataFrame(Londonlist)

# Display the number of rows in the DataFrame
len(LondonDF)

33

In [19]:
# Display the first 10 rows of the DataFrame
LondonDF.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65b953683c56c5f054bb874c,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65b953683c56c5f054bb8a6f,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,65b953693c56c5f054bb95bd,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,65b953693c56c5f054bba3bc,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,65b953693c56c5f054bba3c9,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,65b953693c56c5f054bbaabf,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,65b953693c56c5f054bbcbd2,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
7,65b953693c56c5f054bbcf96,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,65b953693c56c5f054bbcfb3,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,65b953693c56c5f054bbcfb4,295107,0,PI/000020749,City Bar & Grill,Restaurant/Cafe/Canteen,1,London City Airport (Airside),London,,...,http://www.cityoflondon.gov.uk/Corporation/hom...,publicprotection@cityoflondon.gov.uk,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.0479655750095844, 'latitude': ...",,4649.188850,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [10]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query = {'RatingValue':5, 'geocode.latitude':{'$gte':51.48012, '$lte':51.50012},'geocode.longitude':{'$gte':0.07384,'$lte':0.09384}} 
fields = {'geocode.latitude':1, 'geocode.longitude':1,'RatingValue':1, 'scores.Hygiene':1}
sort =  [('scores.Hygiene',1)]

# Print the results
pprint(list(db.establishments.find(query,fields).sort(sort)))

[{'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc571'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc575'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc58e'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5a7'),
  'geocode': {'latitude': 51.4867296, 'longitude': 0.0912164},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5a9'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5af'),
  'geocode': {'latitude': 51.4871632, 'longitude': 0.0916256},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5c5'),
  'geocode': {'latitude': 51.4871406555176, 'longitude': 0.0912820026278496},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5c8'),
  'geocode': {'latitude': 51.4871406555176, 'longitude': 0.0912820026278496},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5ee'),
  'geocode': {'latitude': 51.4877576, 'longitude': 0.091566},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc5f0'),
  'geocode': {'latitude': 51.4871401, 'longitude': 0.0908895},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc62c'),
  'geocode': {'latitude': 51.4878941, 'longitude': 0.0909672},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc644'),
  'geocode': {'latitude': 51.4876894, 'longitude': 0.0905233},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc64a'),
  'geocode': {'latitude': 51.4876718, 'longitude': 0.0903232},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc65f'),
  'geocode': {'latitude': 51.4817109, 'longitude': 0.0840959},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc674'),
  'geocode': {'latitude': 51.487928, 'longitude': 0.0900757},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc696'),
  'geocode': {'latitude': 51.487865447998, 'longitude': 0.0894860029220581},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6a0'),
  'geocode': {'latitude': 51.4880687, 'longitude': 0.0897508},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6a2'),
  'geocode': {'latitude': 51.4881611, 'longitude': 0.089611},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6bd'),
  'geocode': {'latitude': 51.4881627, 'longitude': 0.0895246},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6d3'),
  'geocode': {'latitude': 51.4884195010951, 'longitude': 0.0893575026992294},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6f3'),
  'geocode': {'latitude': 51.4806876203642, 'longitude': 0.0808583091748281},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6f9'),
  'geocode': {'latitude': 51.4827461242676, 'longitude': 0.0831020027399063},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6fa'),
  'geocode': {'latitude': 51.4884997, 'longitude': 0.0887766},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc709'),
  'geocode': {'latitude': 51.4885934, 'longitude': 0.0885648},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc73d'),
  'geocode': {'latitude': 51.4845542907715, 'longitude': 0.0836590006947517},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc73e'),
  'geocode': {'latitude': 51.4810979, 'longitude': 0.0802144},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc74e'),
  'geocode': {'latitude': 51.4806732, 'longitude': 0.0793165},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc75f'),
  'geocode': {'latitude': 51.4860247, 'longitude': 0.0843422},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc76a'),
  'geocode': {'latitude': 51.4890121, 'longitude': 0.0868772},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc76b'),
  'geocode': {'latitude': 51.487438, 'longitude': 0.0852709},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc773'),
  'geocode': {'latitude': 51.4808120727539, 'longitude': 0.0785060003399849},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc77d'),
  'geocode': {'latitude': 51.4838756, 'longitude': 0.0812914},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc78a'),
  'geocode': {'latitude': 51.4847465, 'longitude': 0.0820677},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc791'),
  'geocode': {'latitude': 51.4892216, 'longitude': 0.0861158},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc792'),
  'geocode': {'latitude': 51.4884185791016, 'longitude': 0.0853480026125908},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc794'),
  'geocode': {'latitude': 51.4892023, 'longitude': 0.086187},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7a2'),
  'geocode': {'latitude': 51.484673, 'longitude': 0.0814574},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7bf'),
  'geocode': {'latitude': 51.4896464707035, 'longitude': 0.0857344851907352},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7ca'),
  'geocode': {'latitude': 51.4893348, 'longitude': 0.0853618},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc801'),
  'geocode': {'latitude': 51.4908567, 'longitude': 0.0853967},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc803'),
  'geocode': {'latitude': 51.4900815, 'longitude': 0.0842824},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc806'),
  'geocode': {'latitude': 51.4897501, 'longitude': 0.0839053},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc80e'),
  'geocode': {'latitude': 51.4901495, 'longitude': 0.0839974},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc814'),
  'geocode': {'latitude': 51.4862246, 'longitude': 0.0801741},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc816'),
  'geocode': {'latitude': 51.4873504638672, 'longitude': 0.0810069963335991},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc817'),
  'geocode': {'latitude': 51.4835927, 'longitude': 0.0771598},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc829'),
  'geocode': {'latitude': 51.486075, 'longitude': 0.0789717},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc83b'),
  'geocode': {'latitude': 51.4903258, 'longitude': 0.0824813},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc840'),
  'geocode': {'latitude': 51.4824142456055, 'longitude': 0.074412003159523},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc841'),
  'geocode': {'latitude': 51.4824256896973, 'longitude': 0.0743729993700981},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc84f'),
  'geocode': {'latitude': 51.4863967895508, 'longitude': 0.0776320025324821},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc850'),
  'geocode': {'latitude': 51.4863955, 'longitude': 0.0776292},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc85e'),
  'geocode': {'latitude': 51.4987492, 'longitude': 0.0895991},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc867'),
  'geocode': {'latitude': 51.4989512, 'longitude': 0.0902181},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8ab'),
  'geocode': {'latitude': 51.4871520996094, 'longitude': 0.075984999537468},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8b4'),
  'geocode': {'latitude': 51.4940567016602, 'longitude': 0.0827509984374046},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8c1'),
  'geocode': {'latitude': 51.4950485229492, 'longitude': 0.0835620015859604},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8c8'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8c9'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc920'),
  'geocode': {'latitude': 51.4978398, 'longitude': 0.0844204},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc93e'),
  'geocode': {'latitude': 51.4918377, 'longitude': 0.0774802},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc959'),
  'geocode': {'latitude': 51.4942476, 'longitude': 0.0795886},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc97c'),
  'geocode': {'latitude': 51.4914321899414, 'longitude': 0.075545996427536},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc996'),
  'geocode': {'latitude': 51.4935863, 'longitude': 0.0770593},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc9bc'),
  'geocode': {'latitude': 51.4923133850098, 'longitude': 0.0744580030441284},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc9d9'),
  'geocode': {'latitude': 51.4922421, 'longitude': 0.0739989},
  'scores': {'Hygiene': 0}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc48b'),
  'geocode': {'latitude': 51.480141, 'longitude': 0.089218},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc537'),
  'geocode': {'latitude': 51.4870351, 'longitude': 0.0927429},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc61f'),
  'geocode': {'latitude': 51.4876089, 'longitude': 0.0909382},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc62a'),
  'geocode': {'latitude': 51.4878934, 'longitude': 0.0910104},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc648'),
  'geocode': {'latitude': 51.4877234, 'longitude': 0.0904552},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc64f'),
  'geocode': {'latitude': 51.4876718, 'longitude': 0.0903232},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc67c'),
  'geocode': {'latitude': 51.4817727, 'longitude': 0.083745},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc6d9'),
  'geocode': {'latitude': 51.4804420471191, 'longitude': 0.0812250003218651},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc750'),
  'geocode': {'latitude': 51.4870876, 'longitude': 0.0857591},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc752'),
  'geocode': {'latitude': 51.4810714, 'longitude': 0.0796803},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc757'),
  'geocode': {'latitude': 51.4873374, 'longitude': 0.0858713},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc767'),
  'geocode': {'latitude': 51.4808287, 'longitude': 0.078661},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc779'),
  'geocode': {'latitude': 51.4808120727539, 'longitude': 0.0785060003399849},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7ac'),
  'geocode': {'latitude': 51.4891019, 'longitude': 0.0857646},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7ae'),
  'geocode': {'latitude': 51.489315, 'longitude': 0.0859184},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7b7'),
  'geocode': {'latitude': 51.4893255, 'longitude': 0.0858325},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7d5'),
  'geocode': {'latitude': 51.4893112182617, 'longitude': 0.084697000682354},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7e2'),
  'geocode': {'latitude': 51.4861922, 'longitude': 0.0809311},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc7e8'),
  'geocode': {'latitude': 51.4899426, 'longitude': 0.0846755},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc8c7'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc97a'),
  'geocode': {'latitude': 51.4898490905762, 'longitude': 0.074074998497963},
  'scores': {'Hygiene': 5}},
 {'RatingValue': 5,
  '_id': ObjectId('65b953693c56c5f054bbc991'),
  'geocode': {'latitude': 51.4935863, 'longitude': 0.0770593},
  'scores': {'Hygiene': 5}}]

In [11]:
# Convert result to Pandas DataFrame
results = db.establishments.find(query,fields).sort(sort)
resultslist = []
for x in results:
    resultslist.append(x)

PenangDF = pd.DataFrame(resultslist)
PenangDF

,_id,RatingValue,scores,geocode
0,65b953693c56c5f054bbc571,5,{'Hygiene': 0},"{'longitude': 0.0924199968576431, 'latitude': ..."
1,65b953693c56c5f054bbc575,5,{'Hygiene': 0},"{'longitude': 0.0925370007753372, 'latitude': ..."
2,65b953693c56c5f054bbc58e,5,{'Hygiene': 0},"{'longitude': 0.09208, 'latitude': 51.4873437}"
3,65b953693c56c5f054bbc5a7,5,{'Hygiene': 0},"{'longitude': 0.0912164, 'latitude': 51.4867296}"
4,65b953693c56c5f054bbc5a9,5,{'Hygiene': 0},"{'longitude': 0.0859939977526665, 'latitude': ..."
...,...,...,...,...
83,65b953693c56c5f054bbc7e2,5,{'Hygiene': 5},"{'longitude': 0.0809311, 'latitude': 51.4861922}"
84,65b953693c56c5f054bbc7e8,5,{'Hygiene': 5},"{'longitude': 0.0846755, 'latitude': 51.4899426}"
85,65b953693c56c5f054bbc8c7,5,{'Hygiene': 5},"{'longitude': 0.0787421, 'latitude': 51.4903331}"
86,65b953693c56c5f054bbc97a,5,{'Hygiene': 5},"{'longitude': 0.074074998497963, 'latitude': 5..."
87,65b953693c56c5f054bbc991,5,{'Hygiene': 5},"{'longitude': 0.0770593, 'latitude': 51.4935863}"

In [12]:
#cleaning up the data 
import json
scores = []
latitude = []
longitude = []
for x,y in PenangDF.iterrows():
    scores.append(y['scores']['Hygiene'])
    latitude.append(y['geocode']['latitude'])
    longitude.append(y['geocode']['longitude'])

PenangDF['scores'] = scores
PenangDF['latitude'] = latitude
PenangDF['longitude'] = longitude
del PenangDF['geocode']
PenangDF

#cleaning up the data

                         _id  RatingValue  scores   latitude  longitude
0   65b953693c56c5f054bbc571            5       0  51.487148   0.092420
1   65b953693c56c5f054bbc575            5       0  51.487534   0.092537
2   65b953693c56c5f054bbc58e            5       0  51.487344   0.092080
3   65b953693c56c5f054bbc5a7            5       0  51.486730   0.091216
4   65b953693c56c5f054bbc5a9            5       0  51.481518   0.085994
..                       ...          ...     ...        ...        ...
83  65b953693c56c5f054bbc7e2            5       5  51.486192   0.080931
84  65b953693c56c5f054bbc7e8            5       5  51.489943   0.084676
85  65b953693c56c5f054bbc8c7            5       5  51.490333   0.078742
86  65b953693c56c5f054bbc97a            5       5  51.489849   0.074075
87  65b953693c56c5f054bbc991            5       5  51.493586   0.077059

[88 rows x 5 columns]

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [18]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match = {'$match': {'scores.Hygiene':0}}
# 2. Groups the matches by Local Authority
group = {'$group':{'_id':{'LocalAuthorityName':'$LocalAuthorityName'},'count': {'$sum':1}}}
# 3. Sorts the matches from highest to lowest
sort = {'$sort': {'count': -1}}

# Print the number of documents in the result
pipeline = [match,group,sort]
results = list(establishments.aggregate(pipeline))
len(results)

55

In [17]:
# Print the first 10 results
pprint(results[0:10])

[{'_id': {'LocalAuthorityName': 'Thanet'}, 'count': 1130},
 {'_id': {'LocalAuthorityName': 'Greenwich'}, 'count': 882},
 {'_id': {'LocalAuthorityName': 'Maidstone'}, 'count': 713},
 {'_id': {'LocalAuthorityName': 'Newham'}, 'count': 711},
 {'_id': {'LocalAuthorityName': 'Swale'}, 'count': 686},
 {'_id': {'LocalAuthorityName': 'Chelmsford'}, 'count': 680},
 {'_id': {'LocalAuthorityName': 'Medway'}, 'count': 672},
 {'_id': {'LocalAuthorityName': 'Bexley'}, 'count': 607},
 {'_id': {'LocalAuthorityName': 'Southend-On-Sea'}, 'count': 586},
 {'_id': {'LocalAuthorityName': 'Tendring'}, 'count': 542}]

In [14]:
# Convert the result to a Pandas DataFrame

BadHygiene = pd.DataFrame(results)
BadHygiene
LA = []

for x,y in BadHygiene.iterrows():
    LA.append(y['_id']['LocalAuthorityName'])

BadHygiene['Local Authority'] = LA
del BadHygiene['_id']

BadHygiene = BadHygiene[['Local Authority','count']]
BadHygiene

               Local Authority  count
0                       Thanet   1130
1                    Greenwich    882
2                    Maidstone    713
3                       Newham    711
4                        Swale    686
5                   Chelmsford    680
6                       Medway    672
7                       Bexley    607
8              Southend-On-Sea    586
9                     Tendring    542
10                  Colchester    498
11             Tunbridge Wells    491
12        Folkestone and Hythe    480
13                  Eastbourne    478
14                    Hastings    464
15                     Bromley    460
16                     Ashford    427
17                    Havering    397
18                    Dartford    383
19                   Braintree    382
20                    Basildon    362
21                   Gravesham    339
22       Tonbridge and Malling    325
23                    Thurrock    313
24        Barking and Dagenham    301
25             Canterbury City    298
26                   Brentwood    285
27                Castle Point    281
28                      Harlow    274
29                  Uttlesford    251
30                       Lewes    250
31                   Sevenoaks    223
32                      Maldon    197
33          East Hertfordshire    189
34                    Rochford    187
35                   Redbridge    182
36               Epping Forest    180
37                East Suffolk    159
38              Waltham Forest    110
39                     Babergh     97
40                     Wealden     93
41                      Rother     80
42                    Lewisham     65
43                   Tandridge     42
44  City of London Corporation     28
45                     Ipswich     21
46               Tower Hamlets      9
47         North Hertfordshire      6
48                  Mid Sussex      5
49      Kensington and Chelsea      1
50                  Broxbourne      1
51                     Reading      1
52                      Dorset      1
53               North Norfolk      1
54                  Sunderland      1

In [15]:
# Display the number of rows in the DataFrame


len(BadHygiene)

55

In [16]:
# Display the first 10 rows of the DataFrame
BadHygiene[0:10]

   Local Authority  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542